unstable_features = true

brace_style = "PreferSameLine"
fn_single_line = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
max_width = 120
reorder_impl_items = true
use_field_init_shorthand = true
where_single_line = true

