[package]
name = "rusttracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = { version = "0.25.1", features = ["rayon"] }
indicatif = "0.17.8"
itertools = "0.12.1"
rand = { version = "0.9.0-alpha.1", features = ["small_rng"] }
rayon = "1.10.0"
strum = "0.26.2"
strum_macros = "0.26.2"
derive-new = "0.6.0"

[profile.release]
opt-level = 3
