[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = [
    "lib/geometry",
]

[dependencies]
rand = "0.9.0-alpha.1"
image = "0.25.1"
geometry = { path = "./lib/geometry" }
indicatif = "0.17.8"
